site_name: ""
# Agregar material plugin
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs
    - toc.integrate
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  # Colores y estilos
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: deep purple
      accent: purple
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to night mode
      primary: deep purple
      accent: purple
# Plugins para resaltar y dar formato al bloque de código
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      #linenums: true # no es necesario y tengo mas control para elegir cuando usarlo al definirlo en el bloque
      #guess_lang: false # Desactiva la deteccion automatica del lenguaje
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# Footer
# Social Media
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dariogonzalez-me
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dgonzalezpfaffenzeller
# Copyright
copyright: |
  &copy; 2025 MkDocs | <a href="https://github.com/dariogonzalez-me/documentacion?tab=GPL-3.0-1-ov-file" target="_blank" rel="noopener">Public licence</a>