site_name: MkDocs test
# Agregar material plugin
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs
    - toc.integrate
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  # Colores y estilos
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
# Footer
# Social Media
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dariogonzalez-me
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dgonzalezpfaffenzeller
# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/dariogonzalez-me/documentacion?tab=GPL-3.0-1-ov-file" target="_blank" rel="noopener">MkDocs test - puplic licence</a>